# Configuration inspirée par https://github.com/kaelig/scss-lint-w3c
# adapté pour Clever Age

# Cette configuration reprend tous les settings, même ceux par défaut définis
# ici : https://github.com/causes/scss-lint/blob/master/config/default.yml

scss_files: "**/*.scss"

linters:
  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#bangformat
  # La spec mentionne rarement !important mais semble favoriser un espace avant
  # le point d'exclamation : http://www.w3.org/TR/CSS21/cascade.html#important-rules
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#borderzero
  # Dans la mesure ou nous utilisons indifféremment "border: none" et
  # "border: 0" on ne force pas les choses à ce niveau (ça n'aurait d’intérêt
  # que si l'on souhaite forcer un cohérence pour faire des recherches)
  BorderZero:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorkeyword
  # Nous nous interdisons les mots clé pour les couleurs. On utilisera toujours
  # Les notation plus complètes (hex, rgb, hsl et variable).
  ColorKeyword:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorvariable
  # L'utilisation des variables pour définir les couleurs est obligatoire. Cela
  # nous permet de garantir la modularité de notre code Sass.
  ColorVariable:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#comment
  # On ne veux pas garder de commentaires (`/* */`) dans nos CSS générés,
  # Pour garantir ça, on force l'usage des commentaire Sass (`//`)
  Comment:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/compass/README.md
  # Même si l'on utilise compass, dans la mesure ou nous utilisons autoprefixer
  # il n'est pas utile de forcer l'usage des mixin Compass.
  Compass::PropertyWithMixin:
    enabled: false
    # ignore:
    #   - 'align-content'
    #   - 'align-items'
    #   - 'align-self'
    #   - 'animation'
    #   - 'animation-delay'
    #   - 'animation-direction'
    #   - 'animation-duration'
    #   - 'animation-fill-mode'
    #   - 'animation-iteration-count'
    #   - 'animation-name'
    #   - 'animation-play-state'
    #   - 'animation-timing-function'
    #   - 'appearance'
    #   - 'apply-origin'
    #   - 'background'
    #   - 'background-clip'
    #   - 'background-image'
    #   - 'background-origin'
    #   - 'background-size'
    #   - 'border-bottom-left-radius'
    #   - 'border-bottom-radius'
    #   - 'border-bottom-right-radius'
    #   - 'border-image'
    #   - 'border-left-radius'
    #   - 'border-radius'
    #   - 'border-right-radius'
    #   - 'border-top-left-radius'
    #   - 'border-top-radius'
    #   - 'border-top-right-radius'
    #   - 'box-shadow'
    #   - 'box-sizing'
    #   - 'break-after'
    #   - 'break-before'
    #   - 'break-inside'
    #   - 'column-break'
    #   - 'column-break-after'
    #   - 'column-break-before'
    #   - 'column-break-inside'
    #   - 'column-count'
    #   - 'column-fill'
    #   - 'column-gap'
    #   - 'column-rule'
    #   - 'column-rule-color'
    #   - 'column-rule-style'
    #   - 'column-rule-width'
    #   - 'column-span'
    #   - 'column-width'
    #   - 'columns'
    #   - 'content'
    #   - 'display-flex'
    #   - 'filter'
    #   - 'flex'
    #   - 'flex-basis'
    #   - 'flex-direction'
    #   - 'flex-flow'
    #   - 'flex-grow'
    #   - 'flex-shrink'
    #   - 'flex-wrap'
    #   - 'flexbox'
    #   - 'flow-from'
    #   - 'flow-into'
    #   - 'font-face'
    #   - 'hyphens'
    #   - 'inline-block'
    #   - 'justify-content'
    #   - 'keyframes'
    #   - 'list-style'
    #   - 'list-style-image'
    #   - 'opacity'
    #   - 'order'
    #   - 'selection'
    #   - 'text-shadow'
    #   - 'transform'
    #   - 'transform-origin'
    #   - 'transition'
    #   - 'transition-delay'
    #   - 'transition-duration'
    #   - 'transition-property'
    #   - 'transition-timing-function'
    #   - 'word-break'

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#debugstatement
  # Ça nous permet d'être sure qu'on ne laisse pas trainer de @debug inutile
  DebugStatement:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#declarationorder
  # Ça permet de garantir un cohérence de lisibilité du code d'un projet à
  # l'autre et d'une personne à l'autre.
  DeclarationOrder:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#duplicateproperty
  # Dans la mesure ou ça ne gère pas les exceptions acceptables (background
  # avec couleur hexa et rgba par exemple) on le désactive.
  DuplicateProperty:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#elseplacement
  # Ça permet de garantir la cohérence d'écriture de code. le parti pris et de
  # mettre les `@else` sur un e nouvelle ligne.
  ElsePlacement:
    enabled: true
    style: new_line

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#emptylinebetweenblocks
  # Encore une fois, c'est uniquement pour garantir la cohérence de code
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#emptyrule
  # C'est pour éviter de laisser traîner des trucs qui servent à rien dans le code
  EmptyRule:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#emptyrule
  # C'est pour donner de la cohérence avec les autres fichier (en particulier JS)
  # Le plus simple est de configurer votre éditeur pour qu'il rajoute automatiquement
  # cette ligne vide (c'est la configuration recommandé dans notre fichier .editorconfig)
  FinalNewline:
    enabled: true
    present: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#hexlength
  # On n'impose pas la longueur des couleurs hexadécimal car ça n'a pas d'impact sur la lisibilité
  HexLength:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#hexnotation
  # On n'impose pas la longueur des couleurs hexadécimal car ça n'a pas d'impact sur la lisibilité
  HexNotation:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#hexvalidation
  # Si on écrit des couleurs hexadécimal, on s'assure qu'elle le sont correctement.
  HexValidation:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#idselector
  # En théorie oui, dans la pratique non.
  IdSelector:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#importantrule
  # En théorie oui, dans la pretique non.
  ImportantRule:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#importpath
  # Permet de garantir que les chemin d'import sont toujours écrit de manière normé et compact
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#indentation
  # La encore c'est pour assurer un cohérence avec ce qu'on fait dans d'autre langage.
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    width:     2
    character: space

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#leadingzero
  # Ça ne change pas fondamentalement la lisibilité, on laisse donc chacun faire comme il veut.
  LeadingZero:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#mergeableselector
  # Permet de garantir qu'on ne définie pas deux fois le même sélecteur et qu'à chaque
  # fois qu'on peut faire une imbrication de sélecteur, celle-ci est faite.
  MergeableSelector:
    enabled: true
    force_nesting: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#nameformat
  # Notre convention de nommage pour les mixins et fonctions est
  # "tout en minuscule avec traits d'union comme séparateur".
  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: hyphenated_lowercase

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#nestingdepth
  # On limite l'imbrication des sélecteurs pour éviter d'avoir des sélecteurs trop lourds.
  NestingDepth:
    enabled: true
    max_depth: 5

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#placeholderinextend
  # Even if it's a good idea, we sometimes extend classes
  PlaceholderInExtend:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertycount
  # Nous n'avons pas de règles spécifique sur cette question.
  PropertyCount:
    enabled: false
    # include_nested: false
    # max_properties: 5

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertysortorder
  # Beaucoup trop lourd et sujet à controverse dans notre contexte.
  PropertySortOrder:
    enabled: false
    # ignore_unspecified: false
    # order: nil # Ordre alphabétique
    # separate_groups: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertyspelling
  # On ne vérifie pas l'usage de propriété inconnus
  PropertySpelling:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#qualifyingelement
  # Seul les sélecteurs d'attribut peuvent être spécialisé à l'aide d'un sélecteur d'élément.
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#selectordepth
  # On s'assure qu'on est cohérent avec la règle NestingDepth
  SelectorDepth:
    enabled: true
    max_depth: 5

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#selectorformat
  # Clever Age utilise la convention BEM
  SelectorFormat:
    enabled: false
    # convention: BEM
    # ignored_types:
    # ignored_names:
    # attribute_convention: hyphenated_lowercase
    # class_convention: hyphenated_lowercase
    # id_convention: hyphenated_lowercase
    # placeholder_convention: hyphenated_lowercase

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#shorthand
  # A chaque fois que c'est possible on préférera les notations compact
  Shorthand:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#singlelineperproperty
  # Cette propriété garantie un code plus lisible
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#singlelineperselector
  # Le principale intéret de forcer un selecteur par ligne c'est d'avoir
  # des diff de version GIT plus facile à lire
  SingleLinePerSelector:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#spaceaftercomma
  # Là encore il s'agit d'améliorer la lisibilité
  SpaceAfterComma:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#spaceafterpropertycolon
  # Améliore la lisibilité mais sans être trop contraignant
  SpaceAfterPropertyColon:
    enabled: true
    style: at_least_one_space

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#spaceafterpropertyname
  # Améliore la lisibilité an garantissant que ":" est toujours collé au nom de propriété CSS
  SpaceAfterPropertyName:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#spacebeforebrace
  # La convention est de toujours mettre un espace entre un sélecteur est une accolade
  # On demande a ce que l'accolage soit sur la même ligne que le sélecteur pour que les
  # éditeur de code puisse proposer du folding le plus compact possible.
  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#spacebetweenparens
  # La convention est de ne pas avoir d'espace entre les parenthèses.
  # Ainsi, hsl(0, 100%, 50%) ne sera jamais écris hsl( 0, 100%, 50% )
  SpaceBetweenParens:
    enabled: true
    spaces: 0

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#stringquotes
  # Il n'y a pas de consensus claire sur la question
  StringQuotes:
    enabled: false
    # style: single_quotes # ou double_quotes

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#trailingsemicolon
  # On garantis que les règles se termine toujours bien par un point-virgule
  TrailingSemicolon:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#trailingzero
  # On garantis qu'on ne laisse pas traîner de zéro inutiles
  TrailingZero:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#unnecessarymantissa
  # Même chose que pour la propriété précédente, on ne laisse pas traîner de zéro inutile
  UnnecessaryMantissa:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#unnecessaryparentreference
  # On s'assure qu'on ne met pas de référence & qui ne servent à rien
  UnnecessaryParentReference:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#urlformat
  # On ne force pas de règle particulière sur les URL
  UrlFormat:
    enabled: false

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#urlquotes
  # Cohérence avec d'autre notation Sass
  UrlQuotes:
    enabled: true

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#variableforproperty
  # L'usage de variables n'est pas obligatoire
  VariableForProperty:
    enabled: false
    # properties:
    #   - color
    #   - font

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#vendorprefix
  # Pas de préfixe vendeur dans notre code. On utilise Autoprefixer pour ça.
  VendorPrefixes:
    enabled: true
    identifier_list: base # ou bourbon si on utilise cette bibliothèque
    additional_identifiers: []
    excluded_identifiers: []

  # https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#zerounit
  # On ne met pas d'unité sur la valeur zéro
  ZeroUnit:
    enabled: true
